[ Custom Model Class 정의 및 설계]
- 데이테셋 및 구현방법에 따른 모델 설계
- 부모클래스 : nn.Module
- 필수 오버라이딩 메서드 : 상속 받은 메서드 중 재정의하는 것
    *  _ _init_ _(self)   : 모델 구조/구성 요소 정의 
    * forward(self, data) : 전방향/순방향 학습 기능 메서드

[1] 모듈 로딩 <hr>

In [12]:
import torch                        # tensor, 내장함수 및 클래스 관련 모듈
import torch.nn as nn               # 인공신경망 관련 층, 함수 클래스 모듈
import torch.nn.functional as F     # 인공신경망 관련 층, AF, LF 함수 모듈

import pandas as pd                 # 데이터 로딩 및 전처리 관련 모듈 
import numpy as np                  # raw 데이터 즉, ndarray 데이터 관련 모듈


[2] 커스텀 모델 클래스 설계 <hr>

In [13]:
## [2-1] 고정된 층과 퍼셉트론 구성 모델
## - 데 이  터 셋 : 피쳐 3 , 타겟 1 , 타겟 연속형
## - 학습    방법 : 지도학습 - 회귀
## - 구현알고리즘 : 인공신경망계열 DNN 
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      3        20                ReLU
## - 은닉층      20       10                ReLU
## - 은닉층      10        5                ReLU
## - 출력층       5        1                 -
## -------------------------------------------------
class CustomModel(nn.Module):
    # 인스턴스 초기화 및 생성 메서드
    def __init__(self):
        super().__init__()
        # ANN 층 인스턴스 생성
        self.in_layer=nn.Linear(3, 20)
        self.hd_layer1=nn.Linear(20, 10)
        self.hd_layer2=nn.Linear(10, 5)
        self.out_layer=nn.Linear(5, 1)

    # 순전파 학습 메서드 
    def forward(self, data):
        #- 입력층
        out=self.in_layer(data)      # data * weight + b
        out=F.relu(out)              # AF(data * weight + b) 결과물

        #- 은닉층1
        out=self.hd_layer1(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물        

        #- 은닉층2
        out=self.hd_layer2(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물    

        #- 출력층 : 회귀로 결과 그래도 반환
        out=self.out_layer(out)      # out * weight + b

        return out 
               

In [14]:
## - 모델 사용 -----------------------------------
## 모델 인스턴스 생성 
model=CustomModel()

## 모델 구조 확인
print(model)

CustomModel(
  (in_layer): Linear(in_features=3, out_features=20, bias=True)
  (hd_layer1): Linear(in_features=20, out_features=10, bias=True)
  (hd_layer2): Linear(in_features=10, out_features=5, bias=True)
  (out_layer): Linear(in_features=5, out_features=1, bias=True)
)


In [15]:
## 모델 동작 테스트
data=torch.FloatTensor([[10,5,8],[5,9,7]])
print(data)

## 모델에 데이터 전달
pre=model(data)

tensor([[10.,  5.,  8.],
        [ 5.,  9.,  7.]])


In [16]:
# 모델에 파라미터들
for name, param in model.named_parameters():
	print(name, param)

in_layer.weight Parameter containing:
tensor([[-0.2774, -0.5461, -0.4412],
        [-0.5140, -0.3355,  0.4473],
        [ 0.1118,  0.0015, -0.2563],
        [ 0.0079, -0.2510,  0.3864],
        [-0.1087, -0.1075,  0.4986],
        [-0.4895,  0.5557,  0.4529],
        [-0.1478, -0.1073, -0.4705],
        [-0.4036, -0.0423, -0.2524],
        [ 0.4884,  0.0421,  0.1093],
        [-0.0378,  0.1874,  0.2879],
        [-0.5309, -0.0811,  0.3066],
        [ 0.0934, -0.4725, -0.2482],
        [ 0.4648, -0.5663, -0.5501],
        [ 0.4870,  0.4169,  0.1341],
        [-0.1820, -0.4483, -0.3949],
        [-0.4190,  0.3075, -0.4901],
        [-0.2030,  0.2100, -0.1055],
        [ 0.1576,  0.1419,  0.0252],
        [ 0.0385, -0.1944, -0.4060],
        [ 0.3258,  0.1818, -0.2400]], requires_grad=True)
in_layer.bias Parameter containing:
tensor([ 0.0536,  0.0250, -0.4838, -0.1090, -0.2944,  0.1734,  0.1101,  0.0647,
         0.4084, -0.1466, -0.4278,  0.5294, -0.0436, -0.5571,  0.3496, -0.1794,
     