#### [ Linear Layer ]
- pytorch에서 퍼셉트론 가중치합계(Weighed Sum)을 계산해주는 층 클래스  
- 출력값에 활성화함수(AF) 적용해야 출력값이 됨

[1] 모듈로딩 <hr>

In [1]:
## 모듈로딩
import torch					## 텐서관련 모듈
import torch.nn as nn			## 신경망 관련 모듈
import torch.nn.functional as F	## 활성화 및 신경망 관련 함수들

In [3]:
## 임시 데이터 준비
x_train = torch.randn(2,3)
y_train = torch.randint(1, 5, (2,1))

In [4]:
print(x_train.shape, y_train.shape)

torch.Size([2, 3]) torch.Size([2, 1])


[2] 선형 결합층(Full-Connected Layer : FC Layer)

In [14]:
## 인스턴스 생성
layer = nn.Linear(3, 5)		# 입력 피쳐 수, 출력 결과 수 즉, 퍼셉트론 수

In [15]:
## 가중치 합
output = layer(x_train)		# 입력 (2, 3)
output

tensor([[-0.4278, -0.4877, -0.7374, -0.6069,  0.5444],
        [ 0.6626, -0.6944,  0.6454,  1.2843, -0.1652]],
       grad_fn=<AddmmBackward0>)

In [16]:
## W, b 텐서 확인
print(f'weight => {layer.weight}')
print(f'bias   => {layer.bias}')

weight => Parameter containing:
tensor([[-0.4101,  0.1396,  0.5071],
        [-0.5017, -0.1796, -0.4295],
        [-0.5349, -0.0306,  0.5226],
        [-0.5382, -0.5481,  0.5194],
        [ 0.2623, -0.2587, -0.4243]], requires_grad=True)
bias   => Parameter containing:
tensor([ 0.0763,  0.3343, -0.0476,  0.1043,  0.2457], requires_grad=True)
