[1] 모듈 로딩 <hr>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np

[2] 커스텀 모델 클래스 설계

In [6]:
## [2-1] 고정된 층과 퍼셉트론 구성 모델
## - 데 이  터 셋 : 피쳐 4 , 타겟 1 , 타겟 연속형
## - 학습    방법 : 지도학습 - 회귀
## - 구현알고리즘 : 인공신경망계열 DNN 
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      4        15                ReLU
## - 은닉층      15       13                ReLU
## - 은닉층      13        4                ReLU
## - 은닉층       4        3                ReLU
## - 출력층       3        2                 -
## -------------------------------------------------
class CustomModel(nn.Module):
	# 인스턴스 초기화 및 생성 메서드
	def __init__(self):
		super().__init__()
		# ANN 총 인스턴스 생성
		self.in_layer=nn.Linear(4, 15)
		self.hd_layer1=nn.Linear(15, 13)
		self.hd_layer2=nn.Linear(13, 4)
		self.hd_layer3=nn.Linear(4, 3)
		self.out_layer=nn.Linear(3, 2)

	# 순전파 학습 메서드
	def forward(self, data):
		# - 입력층
		out=self.in_layer(data)		# data * weight + b
		out=F.relu(out)				# AF(data * weight + b) 결과물

		# - 은닉층1
		out=self.hd_layer1(out)		# out * weight + b
		out=F.relu(out)				# AF(out * weight + b) 결과물

		# - 은닉층2
		out=self.hd_layer2(out)		# out * weight + b
		out=F.relu(out)				# AF(out * weight + b) 결과물

		# - 은닉층3
		out=self.hd_layer3(out)		# out * weight + b
		out=F.relu(out)				# AF(out * weight + b) 결과물

		# - 출력층 : 회귀로 결과 그래도 반환
		out=self.out_layer(out)		# out * weight + b

		return out

In [7]:
## - 모델 사용 --------------------------------------
## 모델 인스턴스 생성
model=CustomModel()

## 모델 구조 확인
print(model)

CustomModel(
  (in_layer): Linear(in_features=4, out_features=15, bias=True)
  (hd_layer1): Linear(in_features=15, out_features=13, bias=True)
  (hd_layer2): Linear(in_features=13, out_features=4, bias=True)
  (hd_layer3): Linear(in_features=4, out_features=3, bias=True)
  (out_layer): Linear(in_features=3, out_features=2, bias=True)
)


In [8]:
## 모델 동작 테스트
data = torch.FloatTensor([[9, 24, 5, 4],[2, 8, 4, 1]])
print(data)

## 모델에 데이터 전달
pre=model(data)

tensor([[ 9., 24.,  5.,  4.],
        [ 2.,  8.,  4.,  1.]])


In [9]:
## 모델에 파라미터들
for name, param in model.named_parameters():
	print(name, param)

in_layer.weight Parameter containing:
tensor([[ 0.2388, -0.4544,  0.4623,  0.4678],
        [ 0.3106,  0.4892,  0.2570, -0.4670],
        [-0.2030, -0.0951,  0.4043, -0.2673],
        [-0.3893, -0.1624, -0.1025, -0.1026],
        [-0.3726, -0.0698,  0.2516, -0.2369],
        [ 0.2941, -0.3482,  0.3271,  0.4538],
        [-0.4784,  0.4697,  0.1800, -0.3155],
        [-0.0592, -0.2636, -0.0429, -0.3977],
        [ 0.1664,  0.4033, -0.2777, -0.0898],
        [-0.0477,  0.1233, -0.0371, -0.4681],
        [-0.4633, -0.1982, -0.4319, -0.0503],
        [-0.4172, -0.2397, -0.1840,  0.4627],
        [-0.2143, -0.0306, -0.2689,  0.1062],
        [ 0.0593, -0.2710,  0.1600,  0.1567],
        [ 0.2171, -0.0375, -0.2049, -0.3017]], requires_grad=True)
in_layer.bias Parameter containing:
tensor([ 0.4956,  0.4222,  0.2384,  0.4814, -0.4951, -0.0731, -0.3751,  0.1828,
        -0.2575,  0.2407,  0.3975,  0.1790, -0.0711, -0.2883,  0.0807],
       requires_grad=True)
hd_layer1.weight Parameter containin